MLFLOW_TRACKING_URI=https://dagshub.com/anna352/iris.mlflow
MLFLOW_TRACKING_USERNAME=mlflow-anna
MLFLOW_TRACKING_TOKEN=b626496a47fa7a3661709d80a542b555929f69b5

MODEL_NAME=iris_model
MODEL_ALIAS=champion